var MilitaryType = {
	AID:1,
	SUPPLY:2,
	STRATEGY_ATTACK:3,
	WAKE:4,
};
var MilitaryDatas = [
	{id:1,name:"炎海",belong:Belong.ENEMY,
	type:[MilitaryType.AID, MilitaryType.STRATEGY_ATTACK],
	imageCount:4,
	image:"flame",
	//aids:[25],aidCount:1,
	//strategys:[33],strategyCount:1,
	strategys:[[25,33]],strategyCount:1,
	},
	{id:2,name:"毒云",belong:Belong.ENEMY,
	type:[MilitaryType.AID, MilitaryType.STRATEGY_ATTACK],
	imageCount:4,
	image:"poison",
	aids:[23],aidCount:1,
	strategys:[23],strategyCount:1,
	},
	{id:3,name:"济世",belong:Belong.SELF,
	type:[MilitaryType.SUPPLY],
	imageCount:4,
	image:"poison",
	heals:[50],healCount:1,
	},
	{id:4,name:"机关",belong:Belong.ENEMY,
	type:[MilitaryType.AID],
	imageCount:4,
	image:"poison",
	aids:[23],aidCount:1,
	strategys:[23],strategyCount:1,
	}
];