var EventListConfig = [
{
	id:1,
	name:"桃园结义",
	condition:{
		from:{year:184,month:1},
		to:{year:184,month:1},
		seignior:1,
		generals:[
			{id:1,seignior:1},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[]
	},
	script:"Data/Event/tyjy.txt",
	result:[]
},
{
	id:2,
	name:"一顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml1.txt",
	result:[]
},
{
	id:3,
	name:"二顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml2.txt",
	result:[]
},
{
	id:4,
	name:"三顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:5,
	name:"三顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:6,
	name:"三顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:7,
	name:"三顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:8,
	name:"三顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:9,
	name:"三顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:10,
	name:"三顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:11,
	name:"三顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:12,
	name:"三顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:13,
	name:"三顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
}
];
