var EventListConfig = [
{
	id:1,
	name:"桃园结义",
	condition:{
		from:{year:184,month:1},
		to:{year:184,month:2},
		seignior:604,
		generals:[
			{id:21,seignior:0},
			{id:4,seignior:0},
			{id:19,seignior:0}
		],
		citys:[
			{id:45,seignior:604}
		]
	},
	script:"Data/Event/tyjy.txt",
	result:[
		{type:"changeSeignior", id:21, seignior:604, loyalty:100, city:45},
		{type:"changeSeignior", id:4, seignior:604, loyalty:100, city:45},
		{type:"changeSeignior", id:19, seignior:604, loyalty:100, city:45},
	]
},
{
	id:2,
	name:"反董卓联盟",
	condition:{
		from:{year:190,month:1},
		to:{year:190,month:2},
		seignior:0,
		generals:[
			{id:265,seignior:265},
		],
		citys:[
		]
	},
	script:"Data/Event/fdzlm.txt",
	result:[
		{type:"stopBattle", seigniors:[160,602,451,39,375,1,453,237,8,495,562,446,484,367,408,21,75,144], month:12}
	]
},
{
	id:3,
	name:"五虎上将",
	condition:{
		seignior:0,
		generals:[
		],
		feat_generals:{feat:0,count:5,force:70},
		citys:[
		]
	},
	script:"Data/Event/whsj.txt",
	result:[{type:"reputation",generals:[],reputation:"reputation_tiger"}]
},
{
	id:4,
	name:"吕布殒命",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:[1,21],
		generals:[
			{id:265,seignior:0},//下坯有俘虏吕布
		],
		citys:[
			{id:25,seignior:1},//下坯属曹操
		],
		stopBattle:[
			[1,21],//曹操刘备属停战状态
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{type:"kill_generals",generals:[265]},//吕布死
	]
},
{
	id:5,
	name:"官渡之战",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:6,
	name:"失荆州",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:7,
	name:"出师表",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:8,
	name:"一顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:9,
	name:"二顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:10,
	name:"三顾茅庐",
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:11,
	name:"结局",//远征蛮族,平定蛮族,蛮族年年进贡
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:12,
	name:"结局",//蛮族入侵,战乱四起,最终灭亡
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
},
{
	id:13,
	name:"结局",//天下太平
	condition:{
		from:{year:194,month:1},
		to:{year:194,month:1},
		seignior:1,
		generals:[
			{id:4,seignior:0,city:25},
			{id:2,seignior:1},
			{id:3,seignior:1}
		],
		citys:[
			{id:25,seignior:1},
		]
	},
	script:"Data/Event/sgml3.txt",
	result:[
		{id:4,seignior:1,city:25},
	]
}
];
