var ItemType = {
	HEAL:"item_heal"/*治疗伤兵*/
	,ENLIST:"item_enlist"/*招募新兵*/
	,SUPPLEMENT:"item_supplement"/*从后备兵中补充*/
	,EQUIPMENT:"item_equipment"/*装备*/
};
var ItemSubType = {
	
};
//PositionConfig.Hand 武器
//PositionConfig.Body 身
//PositionConfig.Head 头
//PositionConfig.Foot 脚
//PositionConfig.Accessories 配饰
var ItemDatas = [
	{id:1,name:"草药",type:ItemType.HEAL},
	{id:2,name:"麻沸散",type:ItemType.HEAL},
	{id:3,name:"金创药",type:ItemType.HEAL},
	{id:4,name:"人参",type:ItemType.HEAL},
	{id:5,name:"灵芝草",type:ItemType.HEAL},
	{id:6,name:"募兵符",type:ItemType.ENLIST},
	{id:7,name:"募兵令",type:ItemType.ENLIST},
	{id:8,name:"征兵符",type:ItemType.ENLIST},
	{id:9,name:"征兵令",type:ItemType.ENLIST},
	{id:10,name:"强征兵令",type:ItemType.ENLIST},
	{id:11,name:"招兵符",type:ItemType.SUPPLEMENT},
	{id:12,name:"招兵令",type:ItemType.SUPPLEMENT},
	{id:13,name:"招军符",type:ItemType.SUPPLEMENT},
	{id:14,name:"招军令",type:ItemType.SUPPLEMENT},
	{id:15,name:"强招兵令",type:ItemType.SUPPLEMENT},
	{id:16,name:"方天画戟",type:ItemType.EQUIPMENT,rarity:10,stamp:1,position:PositionConfig.Hand,force:10,defense:10},
	{id:17,name:"丈八蛇矛",type:ItemType.EQUIPMENT,rarity:9,stamp:1,position:PositionConfig.Hand,force:9,breakout:10},
	{id:18,name:"青龙偃月刀",type:ItemType.EQUIPMENT,rarity:9,stamp:1,position:PositionConfig.Hand,force:9,morale:10},
	{id:19,name:"虎头湛金枪",type:ItemType.EQUIPMENT,rarity:8,stamp:1,position:PositionConfig.Hand,force:8,morale:10},
	{id:20,name:"龙胆亮银枪",type:ItemType.EQUIPMENT,rarity:8,stamp:1,position:PositionConfig.Hand,force:8,breakout:10},
	{id:21,name:"万石弓",type:ItemType.EQUIPMENT,rarity:7,stamp:1,position:PositionConfig.Hand,force:7,defense:10},
	{id:22,name:"雌雄双剑",type:ItemType.EQUIPMENT,rarity:7,stamp:1,position:PositionConfig.Hand,force:7,attack:10},
	{id:23,name:"七宝刀",type:ItemType.EQUIPMENT,rarity:6,stamp:1,position:PositionConfig.Hand,force:6,defense:5},
	{id:24,name:"青釭剑",type:ItemType.EQUIPMENT,rarity:6,stamp:1,position:PositionConfig.Hand,force:6,breakout:5},
	{id:25,name:"倚天剑",type:ItemType.EQUIPMENT,rarity:6,stamp:1,position:PositionConfig.Hand,force:6,morale:5},
	{id:26,name:"落日弓",type:ItemType.EQUIPMENT,rarity:5,stamp:1,position:PositionConfig.Hand,force:5},
	{id:27,name:"双铁戟",type:ItemType.EQUIPMENT,rarity:5,stamp:1,position:PositionConfig.Hand,force:5},
	{id:28,name:"古锭刀",type:ItemType.EQUIPMENT,rarity:5,stamp:1,position:PositionConfig.Hand,force:5},
	{id:29,name:"青铜鞭",type:ItemType.EQUIPMENT,rarity:4,stamp:1,position:PositionConfig.Hand,force:4},
	{id:30,name:"涯角枪",type:ItemType.EQUIPMENT,rarity:4,stamp:1,position:PositionConfig.Hand,force:4},
	{id:31,name:"流星锤",type:ItemType.EQUIPMENT,rarity:4,stamp:1,position:PositionConfig.Hand,force:4},
	{id:32,name:"钩镰枪",type:ItemType.EQUIPMENT,rarity:3,stamp:1,position:PositionConfig.Hand,force:3},
	{id:33,name:"三尖两刃刀",type:ItemType.EQUIPMENT,rarity:3,stamp:1,position:PositionConfig.Hand,force:3},
	{id:34,name:"铁蒺藜骨朵",type:ItemType.EQUIPMENT,rarity:3,stamp:1,position:PositionConfig.Hand,force:3},
	{id:35,name:"眉尖刀",type:ItemType.EQUIPMENT,rarity:3,stamp:1,position:PositionConfig.Hand,force:3},
	{id:36,name:"龙舌弓",type:ItemType.EQUIPMENT,rarity:2,stamp:1,position:PositionConfig.Hand,force:2},
	{id:37,name:"铁戟",type:ItemType.EQUIPMENT,rarity:2,stamp:1,position:PositionConfig.Hand,force:2},
	{id:38,name:"大斧",type:ItemType.EQUIPMENT,rarity:2,stamp:1,position:PositionConfig.Hand,force:2},
	{id:39,name:"飞锤",type:ItemType.EQUIPMENT,rarity:2,stamp:1,position:PositionConfig.Hand,force:2},
	{id:40,name:"铁鞭",type:ItemType.EQUIPMENT,rarity:1,stamp:1,position:PositionConfig.Hand,force:1},
	{id:41,name:"铁锤",type:ItemType.EQUIPMENT,rarity:1,stamp:1,position:PositionConfig.Hand,force:1},
	{id:42,name:"铁刀",type:ItemType.EQUIPMENT,rarity:1,stamp:1,position:PositionConfig.Hand,force:1},
	{id:43,name:"铁枪",type:ItemType.EQUIPMENT,rarity:1,stamp:1,position:PositionConfig.Hand,force:1},
	{id:44,name:"兵法二十四篇",type:ItemType.EQUIPMENT,rarity:10,stamp:1,position:PositionConfig.Accessories,intelligence:10},
	{id:45,name:"孙子兵法",type:ItemType.EQUIPMENT,rarity:9,stamp:1,position:PositionConfig.Accessories,intelligence:9},
	{id:46,name:"孟徳新书",type:ItemType.EQUIPMENT,rarity:9,stamp:1,position:PositionConfig.Accessories,intelligence:9},
	{id:47,name:"遁甲天书",type:ItemType.EQUIPMENT,rarity:8,stamp:1,position:PositionConfig.Accessories,intelligence:8},
	{id:48,name:"太平要术",type:ItemType.EQUIPMENT,rarity:8,stamp:1,position:PositionConfig.Accessories,intelligence:8},
	{id:49,name:"六韬",type:ItemType.EQUIPMENT,rarity:7,stamp:1,position:PositionConfig.Accessories,intelligence:7},
	{id:50,name:"三略",type:ItemType.EQUIPMENT,rarity:7,stamp:1,position:PositionConfig.Accessories,intelligence:7},
	{id:51,name:"春秋",type:ItemType.EQUIPMENT,rarity:6,stamp:1,position:PositionConfig.Accessories,intelligence:6},
	{id:52,name:"左传",type:ItemType.EQUIPMENT,rarity:6,stamp:1,position:PositionConfig.Accessories,intelligence:6},
	{id:53,name:"战国策",type:ItemType.EQUIPMENT,rarity:5,stamp:1,position:PositionConfig.Accessories,intelligence:5},
	{id:54,name:"汉书",type:ItemType.EQUIPMENT,rarity:4,stamp:1,position:PositionConfig.Accessories,intelligence:4},
	{id:55,name:"红羽扇",type:ItemType.EQUIPMENT,rarity:3,stamp:1,position:PositionConfig.Hand,intelligence:3},
	{id:56,name:"蓝羽扇 ",type:ItemType.EQUIPMENT,rarity:3,stamp:1,position:PositionConfig.Hand,intelligence:3},
	{id:57,name:"七星剑",type:ItemType.EQUIPMENT,rarity:2,stamp:1,position:PositionConfig.Hand,intelligence:2},
	{id:58,name:"圣者宝剑",type:ItemType.EQUIPMENT,rarity:2,stamp:1,position:PositionConfig.Hand,intelligence:2},
	{id:59,name:"圣拂尘",type:ItemType.EQUIPMENT,rarity:1,stamp:1,position:PositionConfig.Hand,intelligence:1},
	{id:60,name:"暗拂尘",type:ItemType.EQUIPMENT,rarity:1,stamp:1,position:PositionConfig.Hand,intelligence:1},
	{id:61,name:"乌金甲",type:ItemType.EQUIPMENT,rarity:10,stamp:1,position:PositionConfig.Body,command:10},
	{id:62,name:"黄金铠",type:ItemType.EQUIPMENT,rarity:9,stamp:1,position:PositionConfig.Body,command:9},
	{id:63,name:"白银铠",type:ItemType.EQUIPMENT,rarity:8,stamp:1,position:PositionConfig.Body,command:8},
	{id:64,name:"龙鳞铠",type:ItemType.EQUIPMENT,rarity:7,stamp:1,position:PositionConfig.Body,command:7},
	{id:65,name:"连环铠",type:ItemType.EQUIPMENT,rarity:6,stamp:1,position:PositionConfig.Body,command:6},
	{id:66,name:"锁子甲",type:ItemType.EQUIPMENT,rarity:5,stamp:1,position:PositionConfig.Body,command:5},
	{id:67,name:"柳叶甲",type:ItemType.EQUIPMENT,rarity:4,stamp:1,position:PositionConfig.Body,command:4},
	{id:68,name:"玲珑铠",type:ItemType.EQUIPMENT,rarity:3,stamp:1,position:PositionConfig.Body,command:3},
	{id:69,name:"青铜铠",type:ItemType.EQUIPMENT,rarity:2,stamp:1,position:PositionConfig.Body,command:2},
	{id:70,name:"铁铠",type:ItemType.EQUIPMENT,rarity:1,stamp:1,position:PositionConfig.Body,command:1},
	{id:71,name:"赤兔",type:ItemType.EQUIPMENT,rarity:10,stamp:1,position:PositionConfig.Foot,agility:10},
	{id:72,name:"乌骓",type:ItemType.EQUIPMENT,rarity:9,stamp:1,position:PositionConfig.Foot,agility:9},
	{id:73,name:"的卢",type:ItemType.EQUIPMENT,rarity:8,stamp:1,position:PositionConfig.Foot,agility:8},
	{id:74,name:"汗血宝马",type:ItemType.EQUIPMENT,rarity:7,stamp:1,position:PositionConfig.Foot,agility:7},
	{id:75,name:"绝影",type:ItemType.EQUIPMENT,rarity:6,stamp:1,position:PositionConfig.Foot,agility:6},
	{id:76,name:"爪黄飞电",type:ItemType.EQUIPMENT,rarity:5,stamp:1,position:PositionConfig.Foot,agility:5},
	{id:77,name:"照夜玉狮子",type:ItemType.EQUIPMENT,rarity:4,stamp:1,position:PositionConfig.Foot,agility:4},
	{id:78,name:"黄骠马",type:ItemType.EQUIPMENT,rarity:3,stamp:1,position:PositionConfig.Foot,agility:3},
	{id:79,name:"大宛马",type:ItemType.EQUIPMENT,rarity:2,stamp:1,position:PositionConfig.Foot,agility:2},
	{id:80,name:"白马",type:ItemType.EQUIPMENT,rarity:1,stamp:1,position:PositionConfig.Foot,agility:1},
	{id:81,name:"凤翅紫金冠",type:ItemType.EQUIPMENT,rarity:10,stamp:1,position:PositionConfig.Head,luck:10},
	{id:82,name:"黄金盔",type:ItemType.EQUIPMENT,rarity:9,stamp:1,position:PositionConfig.Head,luck:9},
	{id:83,name:"夜明盔",type:ItemType.EQUIPMENT,rarity:8,stamp:1,position:PositionConfig.Head,luck:8},
	{id:84,name:"将军盔",type:ItemType.EQUIPMENT,rarity:7,stamp:1,position:PositionConfig.Head,luck:7},
	{id:85,name:"通天冠",type:ItemType.EQUIPMENT,rarity:6,stamp:1,position:PositionConfig.Head,luck:6},
	{id:86,name:"五梁冠",type:ItemType.EQUIPMENT,rarity:5,stamp:1,position:PositionConfig.Head,luck:5},
	{id:87,name:"铜盔",type:ItemType.EQUIPMENT,rarity:4,stamp:1,position:PositionConfig.Head,luck:4},
	{id:88,name:"铁盔",type:ItemType.EQUIPMENT,rarity:3,stamp:1,position:PositionConfig.Head,luck:3},
	{id:89,name:"皮盔",type:ItemType.EQUIPMENT,rarity:2,stamp:1,position:PositionConfig.Head,luck:2},
	{id:90,name:"头巾",type:ItemType.EQUIPMENT,rarity:1,stamp:1,position:PositionConfig.Head,luck:1}
];